/*
 * This file is generated by jOOQ.
 */
package com.advertisement.auth.model.jooq.tables.references


import com.advertisement.auth.model.jooq.tables.AppClients
import com.advertisement.auth.model.jooq.tables.Otp
import com.advertisement.auth.model.jooq.tables.RefreshToken
import com.advertisement.auth.model.jooq.tables.Roles
import com.advertisement.auth.model.jooq.tables.Users
import com.advertisement.auth.model.jooq.tables.UsersRoles



/**
 * The table <code>advertisement.app_clients</code>.
 */
val APP_CLIENTS: AppClients = AppClients.APP_CLIENTS

/**
 * The table <code>advertisement.otp</code>.
 */
val OTP: Otp = Otp.OTP

/**
 * The table <code>advertisement.refresh_token</code>.
 */
val REFRESH_TOKEN: RefreshToken = RefreshToken.REFRESH_TOKEN

/**
 * The table <code>advertisement.roles</code>.
 */
val ROLES: Roles = Roles.ROLES

/**
 * The table <code>advertisement.users</code>.
 */
val USERS: Users = Users.USERS

/**
 * The table <code>advertisement.users_roles</code>.
 */
val USERS_ROLES: UsersRoles = UsersRoles.USERS_ROLES
