server:
  port: 8081
spring:
  application.name: auth-service
  r2dbc:
    url: ${POSTGRES_R2DBC_URL:r2dbc:postgresql://localhost:25432/local-docker-db}
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
    default-schema: advertisement
    liquibase-schema: advertisement
    url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:25432/local-docker-db}
    user: postgres
    password: postgres
    show-summary-output: all

security:
  internal-auth:
    registration-key: 22]Rb8L7z9yityA_nH6-t-pxVd8#q%
    hashing-salt: 8b8L7z9yi#q%]_nH6-t-pxVd22RtyA
  otp:
    hashing-salt: _nH6-t-pxVd8#q%]22Rb8L7z9yityA
    lifetime-seconds: 300
  jwt:
    access-token:
      rsa-public-key-base64: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0NCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBd1h4OFRacWlPRWM3V1ozRDQybWYNCmxYV2pjVUx6VHJ6RVdnZHVjTmRKSHY1YnU1Q2hXQzdPY3ZKY0h2VE9pSVpUcndQM3IxdDFuTklOVi9sbzNta1gNCmtDS2dJT1R6Y3hEOWJtVEVOR0NtOEVwREYxQldUME4wcWpzTTAwSm9wdXllYjlzcEVJcm1HZHVsQmM2Zk1hNjkNCndVdzlKV3hEMjB0K1QzYUgrUy81eTZ1QXU4RjhyZXFFVGNvRFNkWUpmblI1ZVRZTnliNFljTFR3SG5lc21LY0oNCldPdXpuNll4UXk5MmltMzJONmpmOGQrTVV0dFl2VXJGUTU4aktmUndGWlVyMWNIeWNzQmdjNmlXU3l0dzBlWlUNClNyVjhUTGtXQWw1NlpGZmpIMkY5WmdQNEM4M2d1V0tkU2E1aTYySEIvaFk0aUtCWThQQnkwVUkvaWFrL0JJcjUNCmt3SURBUUFCDQotLS0tLUVORCBQVUJMSUMgS0VZLS0tLS0NCg==
      rsa-private-key-base64: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tDQpNSUlFdkFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLWXdnZ1NpQWdFQUFvSUJBUURCZkh4Tm1xSTRSenRaDQpuY1BqYVorVmRhTnhRdk5Pdk1SYUIyNXcxMGtlL2x1N2tLRllMczV5OGx3ZTlNNklobE92QS9ldlczV2MwZzFYDQorV2plYVJlUUlxQWc1UE56RVAxdVpNUTBZS2J3U2tNWFVGWlBRM1NxT3d6VFFtaW03SjV2MnlrUWl1WVoyNlVGDQp6cDh4cnIzQlREMGxiRVBiUzM1UGRvZjVML25McTRDN3dYeXQ2b1JOeWdOSjFnbCtkSGw1TmczSnZoaHd0UEFlDQpkNnlZcHdsWTY3T2ZwakZETDNhS2JmWTNxTi94MzR4UzIxaTlTc1ZEbnlNcDlIQVZsU3ZWd2ZKeXdHQnpxSlpMDQpLM0RSNWxSS3RYeE11UllDWG5wa1YrTWZZWDFtQS9nTHplQzVZcDFKcm1MclljSCtGamlJb0ZqdzhITFJRaitKDQpxVDhFaXZtVEFnTUJBQUVDZ2dFQUF4blYrdFJyUnlXZnhqYm92Y3ROT3gybDMwUjl3Um1ndC9uOTJNeDFKK0dzDQpZZ2JXWHlNWTUwUzFHZXM5MHMybS9RWVRsbm1MeFZYNTBCck0yeUQvWWdMOERWV1RXcGtVeHJaOHQ5all0QlNCDQo4TUlMMnJ5dnNQbG9vallpbHBKSGs4UUZGaUVlYTU4Qk43cEdXT0IrWldFREZkektBRWk4ZEgrU0p2bmxoMUJvDQpNSEY0WEpzWUxzZXh1S3JEOUpEbk5BNFZFRFFOMnc2MWpSRkFDK2dESkFPQnc4OFEzN3ZyTk5sK3JqL2czc3lyDQpjMG5mSmhyYzIwc0hSWDhGNTUvSm1qNnI1TWovRnI3UU5wVUhJMVpJQk0ycE56Y2VXdmIyb3hpYmk2Y0t5QUZ2DQpDbi9adnBodzB2T2dLYkkvb216RnBhOUpuYWNSbnQ0L3pUbHp2aGFaOFFLQmdRRHQ2b2FrcGNoOEJrbGRBUEo2DQpjRXdtb0ZwUzUyN08wUjRjTmVyUmY5N3E3R2xqbTZGQjQyR1JZeHk1eVJRSjBSY004VzVoUVorMHF0aUtrUkxwDQowRnJpaHVYTDBsSXNvZkx1N0xWMzVxaG5uc2wxNW9CWFBLc2NlL0FTQlFvdHRDRDE0MWZGWjRMdTFmbmU3NlNSDQpRVzZQMzFwbXpCa0VmVEQxVXMvekJZRWtPUUtCZ1FEUU1XeXhxb0tGUTJPYXZjTDlvUUFBWlFRVVdHanlRa082DQpzaXBIY0MrY3dJVWcrc3gzYk85aDFxSXdPZllqT2RaVVZOWG9ud0d1TEJsb25kaW5CRG5uK0VTdG44NnJlUzFxDQo2SVJXNlJ2TDZOb1F2MWlkeEZLenhLNEVqRmlCWjVQSXZCdTBNWk1nNlJNT1EzVmZDMXpReEFTM0EwaUpqMzBaDQptSnJVQjVFRUt3S0JnQStHejdTdEVSRnZBNWlyT0NmZmJralREREgrNG85aXZGbFE5M3Ntb2pDb3J4UU9FdzhPDQp2TTVWTG9tOVlxNWxVK0RIWE5IQ0M1OHB5eW4zMzhrY2pPSGR0ZCtBWVZhQ1Z5MWFpMWxBMTFxejFTZjVuQVNWDQpkQUZPNFZMN3V6ZFNXeGhROXVodUlmQmVUSWxORUd0ZVhzM0s0TVoycVdkT21FUmFYREhhK1J1WkFvR0FQM1ZSDQpORFpNNG1IUUVuS1U1TW9XUGdpTVhjYzA5ZUxNMGpOTVA4b3FPUlZWZnQvelF0T3BnNkR3ZnRLcis4QzlXNmNnDQpMRytMQzVQVml0WFNHOVpsOEJiMG1CZUYzeTVvY1pXK0FOKzg0VUp3ZFhwZGdIayszQnl2RGlQWk5saGo2Mk9xDQo3aG5PUnRIRVJTeTZzZVc4dk1XQ3ltWHR6a0EyV1g3eWNuNTc3VkVDZ1lCK1NEbGczUlpPb0dVeGtMblAwTnFrDQoxSmVaM1ZnejdNdVMyNVRIOWx1ZU5QWVdVR01aTTZnY0crc1hvVFNsK1BuVHArelJ4OXAvSzg2WU1IZy9XQlJwDQozQzMwbVpMQ0FLTEVPQUd6Qk9zM3l0VDRYRzNjajlFb3NlMmdYVVNkbVZ1UnlHZUFic1RzRDFFc0xHMW9NSTNvDQpyMDJYalE3NGFmT21GUThjWUUwckFBPT0NCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0NCg==
      lifetime-seconds: 3600 # 1 hour
    refresh-token:
      rsa-public-key-base64: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0NCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBd1h4OFRacWlPRWM3V1ozRDQybWYNCmxYV2pjVUx6VHJ6RVdnZHVjTmRKSHY1YnU1Q2hXQzdPY3ZKY0h2VE9pSVpUcndQM3IxdDFuTklOVi9sbzNta1gNCmtDS2dJT1R6Y3hEOWJtVEVOR0NtOEVwREYxQldUME4wcWpzTTAwSm9wdXllYjlzcEVJcm1HZHVsQmM2Zk1hNjkNCndVdzlKV3hEMjB0K1QzYUgrUy81eTZ1QXU4RjhyZXFFVGNvRFNkWUpmblI1ZVRZTnliNFljTFR3SG5lc21LY0oNCldPdXpuNll4UXk5MmltMzJONmpmOGQrTVV0dFl2VXJGUTU4aktmUndGWlVyMWNIeWNzQmdjNmlXU3l0dzBlWlUNClNyVjhUTGtXQWw1NlpGZmpIMkY5WmdQNEM4M2d1V0tkU2E1aTYySEIvaFk0aUtCWThQQnkwVUkvaWFrL0JJcjUNCmt3SURBUUFCDQotLS0tLUVORCBQVUJMSUMgS0VZLS0tLS0NCg==
      rsa-private-key-base64: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tDQpNSUlFdkFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLWXdnZ1NpQWdFQUFvSUJBUURCZkh4Tm1xSTRSenRaDQpuY1BqYVorVmRhTnhRdk5Pdk1SYUIyNXcxMGtlL2x1N2tLRllMczV5OGx3ZTlNNklobE92QS9ldlczV2MwZzFYDQorV2plYVJlUUlxQWc1UE56RVAxdVpNUTBZS2J3U2tNWFVGWlBRM1NxT3d6VFFtaW03SjV2MnlrUWl1WVoyNlVGDQp6cDh4cnIzQlREMGxiRVBiUzM1UGRvZjVML25McTRDN3dYeXQ2b1JOeWdOSjFnbCtkSGw1TmczSnZoaHd0UEFlDQpkNnlZcHdsWTY3T2ZwakZETDNhS2JmWTNxTi94MzR4UzIxaTlTc1ZEbnlNcDlIQVZsU3ZWd2ZKeXdHQnpxSlpMDQpLM0RSNWxSS3RYeE11UllDWG5wa1YrTWZZWDFtQS9nTHplQzVZcDFKcm1MclljSCtGamlJb0ZqdzhITFJRaitKDQpxVDhFaXZtVEFnTUJBQUVDZ2dFQUF4blYrdFJyUnlXZnhqYm92Y3ROT3gybDMwUjl3Um1ndC9uOTJNeDFKK0dzDQpZZ2JXWHlNWTUwUzFHZXM5MHMybS9RWVRsbm1MeFZYNTBCck0yeUQvWWdMOERWV1RXcGtVeHJaOHQ5all0QlNCDQo4TUlMMnJ5dnNQbG9vallpbHBKSGs4UUZGaUVlYTU4Qk43cEdXT0IrWldFREZkektBRWk4ZEgrU0p2bmxoMUJvDQpNSEY0WEpzWUxzZXh1S3JEOUpEbk5BNFZFRFFOMnc2MWpSRkFDK2dESkFPQnc4OFEzN3ZyTk5sK3JqL2czc3lyDQpjMG5mSmhyYzIwc0hSWDhGNTUvSm1qNnI1TWovRnI3UU5wVUhJMVpJQk0ycE56Y2VXdmIyb3hpYmk2Y0t5QUZ2DQpDbi9adnBodzB2T2dLYkkvb216RnBhOUpuYWNSbnQ0L3pUbHp2aGFaOFFLQmdRRHQ2b2FrcGNoOEJrbGRBUEo2DQpjRXdtb0ZwUzUyN08wUjRjTmVyUmY5N3E3R2xqbTZGQjQyR1JZeHk1eVJRSjBSY004VzVoUVorMHF0aUtrUkxwDQowRnJpaHVYTDBsSXNvZkx1N0xWMzVxaG5uc2wxNW9CWFBLc2NlL0FTQlFvdHRDRDE0MWZGWjRMdTFmbmU3NlNSDQpRVzZQMzFwbXpCa0VmVEQxVXMvekJZRWtPUUtCZ1FEUU1XeXhxb0tGUTJPYXZjTDlvUUFBWlFRVVdHanlRa082DQpzaXBIY0MrY3dJVWcrc3gzYk85aDFxSXdPZllqT2RaVVZOWG9ud0d1TEJsb25kaW5CRG5uK0VTdG44NnJlUzFxDQo2SVJXNlJ2TDZOb1F2MWlkeEZLenhLNEVqRmlCWjVQSXZCdTBNWk1nNlJNT1EzVmZDMXpReEFTM0EwaUpqMzBaDQptSnJVQjVFRUt3S0JnQStHejdTdEVSRnZBNWlyT0NmZmJralREREgrNG85aXZGbFE5M3Ntb2pDb3J4UU9FdzhPDQp2TTVWTG9tOVlxNWxVK0RIWE5IQ0M1OHB5eW4zMzhrY2pPSGR0ZCtBWVZhQ1Z5MWFpMWxBMTFxejFTZjVuQVNWDQpkQUZPNFZMN3V6ZFNXeGhROXVodUlmQmVUSWxORUd0ZVhzM0s0TVoycVdkT21FUmFYREhhK1J1WkFvR0FQM1ZSDQpORFpNNG1IUUVuS1U1TW9XUGdpTVhjYzA5ZUxNMGpOTVA4b3FPUlZWZnQvelF0T3BnNkR3ZnRLcis4QzlXNmNnDQpMRytMQzVQVml0WFNHOVpsOEJiMG1CZUYzeTVvY1pXK0FOKzg0VUp3ZFhwZGdIayszQnl2RGlQWk5saGo2Mk9xDQo3aG5PUnRIRVJTeTZzZVc4dk1XQ3ltWHR6a0EyV1g3eWNuNTc3VkVDZ1lCK1NEbGczUlpPb0dVeGtMblAwTnFrDQoxSmVaM1ZnejdNdVMyNVRIOWx1ZU5QWVdVR01aTTZnY0crc1hvVFNsK1BuVHArelJ4OXAvSzg2WU1IZy9XQlJwDQozQzMwbVpMQ0FLTEVPQUd6Qk9zM3l0VDRYRzNjajlFb3NlMmdYVVNkbVZ1UnlHZUFic1RzRDFFc0xHMW9NSTNvDQpyMDJYalE3NGFmT21GUThjWUUwckFBPT0NCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0NCg==
      lifetime-seconds: 2592000 # 30 days
      hashing-salt: _nH6-t-pxVd8#q%]22Rb8L7z9yityA

sms-service:
  base-url: ${SMS_SERVICE_URL:http://localhost:8484}
  get-token-path: api/token
  send-sms-path: api/sms
  username: advertisement-user
  password: advertisement-password
  retry:
    max-attempts: 3
    min-backoff-seconds: 2

tracing:
  url: ${TRACING_URL:http://127.0.0.1:4317}
loki:
  url: ${LOKI_URL:http://localhost:3100/loki/api/v1/push}

management:
  metrics.distribution.percentiles-histogram.http.server.requests: true
  endpoints.web.exposure.include: '*' # health,info,prometheus
  tracing:
    enabled: true
    sampling.probability: 1.0

logging:
  pattern.level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  console: "[${spring.application.name:}] %clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    org.springframework: INFO
    org.springframework.security: INFO
    com.advertisement.auth: INFO
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters