server:
  port: 8083
spring:
  application:
    name: saga-orchestrator
  r2dbc:
    url: ${POSTGRES_R2DBC_URL:r2dbc:postgresql://localhost:25432/local-docker-db}
    username: postgres
    password: postgres

target: ${TEMPORAL_URL:127.0.0.1:7233}

security:
  internal-auth:
    username: ads-client
    password: tFxE9638'*

tracing:
  url: ${TRACING_URL:http://127.0.0.1:4317}
loki:
  url: ${LOKI_URL:http://localhost:3100/loki/api/v1/push}

management:
  metrics.distribution.percentiles-histogram.http.server.requests: true
  endpoints.web.exposure.include: '*' # health,info,prometheus
  tracing:
    enabled: true
    sampling.probability: 1.0

logging:
  pattern.level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  console: "[${spring.application.name:}] %clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    org.springframework: INFO
    org.springframework.security: INFO
    com.advertisement: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters