/*
 * This file is generated by jOOQ.
 */
package com.advertisement.auth.model.jooq.tables


import com.advertisement.auth.model.jooq.Advertisement
import com.advertisement.auth.model.jooq.keys.APP_CLIENTS_NAME_KEY
import com.advertisement.auth.model.jooq.keys.APP_CLIENTS_PKEY
import com.advertisement.auth.model.jooq.tables.records.AppClientsRecord

import java.time.Instant
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AppClients(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, AppClientsRecord>?,
    parentPath: InverseForeignKey<out Record, AppClientsRecord>?,
    aliased: Table<AppClientsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<AppClientsRecord>(
    alias,
    Advertisement.ADVERTISEMENT,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>advertisement.app_clients</code>
         */
        val APP_CLIENTS: AppClients = AppClients()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AppClientsRecord> = AppClientsRecord::class.java

    /**
     * The column <code>advertisement.app_clients.id</code>.
     */
    val ID: TableField<AppClientsRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>advertisement.app_clients.name</code>.
     */
    val NAME: TableField<AppClientsRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>advertisement.app_clients.password</code>.
     */
    val PASSWORD: TableField<AppClientsRecord, ByteArray?> = createField(DSL.name("password"), SQLDataType.BLOB.nullable(false), this, "")

    /**
     * The column <code>advertisement.app_clients.disabled</code>.
     */
    val DISABLED: TableField<AppClientsRecord, Boolean?> = createField(DSL.name("disabled"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    /**
     * The column <code>advertisement.app_clients.created_at</code>.
     */
    val CREATED_AT: TableField<AppClientsRecord, Instant?> = createField(DSL.name("created_at"), SQLDataType.INSTANT.nullable(false), this, "")

    /**
     * The column <code>advertisement.app_clients.disabled_at</code>.
     */
    val DISABLED_AT: TableField<AppClientsRecord, Instant?> = createField(DSL.name("disabled_at"), SQLDataType.INSTANT, this, "")

    private constructor(alias: Name, aliased: Table<AppClientsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<AppClientsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<AppClientsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>advertisement.app_clients</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>advertisement.app_clients</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>advertisement.app_clients</code> table reference
     */
    constructor(): this(DSL.name("app_clients"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Advertisement.ADVERTISEMENT
    override fun getPrimaryKey(): UniqueKey<AppClientsRecord> = APP_CLIENTS_PKEY
    override fun getUniqueKeys(): List<UniqueKey<AppClientsRecord>> = listOf(APP_CLIENTS_NAME_KEY)
    override fun `as`(alias: String): AppClients = AppClients(DSL.name(alias), this)
    override fun `as`(alias: Name): AppClients = AppClients(alias, this)
    override fun `as`(alias: Table<*>): AppClients = AppClients(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): AppClients = AppClients(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): AppClients = AppClients(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): AppClients = AppClients(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): AppClients = AppClients(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): AppClients = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): AppClients = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): AppClients = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): AppClients = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): AppClients = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): AppClients = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): AppClients = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): AppClients = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): AppClients = where(DSL.notExists(select))
}
