/*
 * This file is generated by jOOQ.
 */
package com.advertisement.auth.model.jooq.tables


import com.advertisement.auth.model.jooq.Advertisement
import com.advertisement.auth.model.jooq.keys.OTP_PKEY
import com.advertisement.auth.model.jooq.tables.records.OtpRecord

import java.time.Instant
import java.util.UUID

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Otp(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, OtpRecord>?,
    parentPath: InverseForeignKey<out Record, OtpRecord>?,
    aliased: Table<OtpRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<OtpRecord>(
    alias,
    Advertisement.ADVERTISEMENT,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>advertisement.otp</code>
         */
        val OTP: Otp = Otp()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<OtpRecord> = OtpRecord::class.java

    /**
     * The column <code>advertisement.otp.id</code>.
     */
    val ID: TableField<OtpRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>advertisement.otp.phone</code>.
     */
    val PHONE: TableField<OtpRecord, String?> = createField(DSL.name("phone"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>advertisement.otp.otp_hash</code>.
     */
    val OTP_HASH: TableField<OtpRecord, ByteArray?> = createField(DSL.name("otp_hash"), SQLDataType.BLOB.nullable(false), this, "")

    /**
     * The column <code>advertisement.otp.type</code>.
     */
    val TYPE: TableField<OtpRecord, String?> = createField(DSL.name("type"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>advertisement.otp.created_at</code>.
     */
    val CREATED_AT: TableField<OtpRecord, Instant?> = createField(DSL.name("created_at"), SQLDataType.INSTANT.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<OtpRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<OtpRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<OtpRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>advertisement.otp</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>advertisement.otp</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>advertisement.otp</code> table reference
     */
    constructor(): this(DSL.name("otp"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Advertisement.ADVERTISEMENT
    override fun getPrimaryKey(): UniqueKey<OtpRecord> = OTP_PKEY
    override fun `as`(alias: String): Otp = Otp(DSL.name(alias), this)
    override fun `as`(alias: Name): Otp = Otp(alias, this)
    override fun `as`(alias: Table<*>): Otp = Otp(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Otp = Otp(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Otp = Otp(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Otp = Otp(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Otp = Otp(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Otp = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Otp = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Otp = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Otp = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Otp = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Otp = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Otp = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Otp = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Otp = where(DSL.notExists(select))
}
