/*
 * This file is generated by jOOQ.
 */
package com.advertisement.auth.model.jooq.tables


import com.advertisement.auth.model.jooq.Advertisement
import com.advertisement.auth.model.jooq.keys.REFRESH_TOKEN_PKEY
import com.advertisement.auth.model.jooq.keys.REFRESH_TOKEN__REFRESH_TOKEN_USER_ID_FK
import com.advertisement.auth.model.jooq.tables.Users.UsersPath
import com.advertisement.auth.model.jooq.tables.records.RefreshTokenRecord

import java.time.Instant
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class RefreshToken(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, RefreshTokenRecord>?,
    parentPath: InverseForeignKey<out Record, RefreshTokenRecord>?,
    aliased: Table<RefreshTokenRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<RefreshTokenRecord>(
    alias,
    Advertisement.ADVERTISEMENT,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>advertisement.refresh_token</code>
         */
        val REFRESH_TOKEN: RefreshToken = RefreshToken()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<RefreshTokenRecord> = RefreshTokenRecord::class.java

    /**
     * The column <code>advertisement.refresh_token.id</code>.
     */
    val ID: TableField<RefreshTokenRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>advertisement.refresh_token.user_id</code>.
     */
    val USER_ID: TableField<RefreshTokenRecord, UUID?> = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>advertisement.refresh_token.refresh_token_hash</code>.
     */
    val REFRESH_TOKEN_HASH: TableField<RefreshTokenRecord, ByteArray?> = createField(DSL.name("refresh_token_hash"), SQLDataType.BLOB.nullable(false), this, "")

    /**
     * The column <code>advertisement.refresh_token.revoked</code>.
     */
    val REVOKED: TableField<RefreshTokenRecord, Boolean?> = createField(DSL.name("revoked"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    /**
     * The column <code>advertisement.refresh_token.created_at</code>.
     */
    val CREATED_AT: TableField<RefreshTokenRecord, Instant?> = createField(DSL.name("created_at"), SQLDataType.INSTANT.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<RefreshTokenRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<RefreshTokenRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<RefreshTokenRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>advertisement.refresh_token</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>advertisement.refresh_token</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>advertisement.refresh_token</code> table reference
     */
    constructor(): this(DSL.name("refresh_token"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, RefreshTokenRecord>?, parentPath: InverseForeignKey<out Record, RefreshTokenRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, REFRESH_TOKEN, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class RefreshTokenPath : RefreshToken, Path<RefreshTokenRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, RefreshTokenRecord>?, parentPath: InverseForeignKey<out Record, RefreshTokenRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<RefreshTokenRecord>): super(alias, aliased)
        override fun `as`(alias: String): RefreshTokenPath = RefreshTokenPath(DSL.name(alias), this)
        override fun `as`(alias: Name): RefreshTokenPath = RefreshTokenPath(alias, this)
        override fun `as`(alias: Table<*>): RefreshTokenPath = RefreshTokenPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Advertisement.ADVERTISEMENT
    override fun getPrimaryKey(): UniqueKey<RefreshTokenRecord> = REFRESH_TOKEN_PKEY
    override fun getReferences(): List<ForeignKey<RefreshTokenRecord, *>> = listOf(REFRESH_TOKEN__REFRESH_TOKEN_USER_ID_FK)

    private lateinit var _users: UsersPath

    /**
     * Get the implicit join path to the <code>advertisement.users</code> table.
     */
    fun users(): UsersPath {
        if (!this::_users.isInitialized)
            _users = UsersPath(this, REFRESH_TOKEN__REFRESH_TOKEN_USER_ID_FK, null)

        return _users;
    }

    val users: UsersPath
        get(): UsersPath = users()
    override fun `as`(alias: String): RefreshToken = RefreshToken(DSL.name(alias), this)
    override fun `as`(alias: Name): RefreshToken = RefreshToken(alias, this)
    override fun `as`(alias: Table<*>): RefreshToken = RefreshToken(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): RefreshToken = RefreshToken(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): RefreshToken = RefreshToken(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): RefreshToken = RefreshToken(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): RefreshToken = RefreshToken(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): RefreshToken = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): RefreshToken = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): RefreshToken = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): RefreshToken = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): RefreshToken = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): RefreshToken = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): RefreshToken = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): RefreshToken = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): RefreshToken = where(DSL.notExists(select))
}
