/*
 * This file is generated by jOOQ.
 */
package com.advertisement.auth.model.jooq.tables


import com.advertisement.auth.model.jooq.Advertisement
import com.advertisement.auth.model.jooq.keys.ROLES_PKEY
import com.advertisement.auth.model.jooq.keys.USERS_ROLES__ROLE_ID_FK
import com.advertisement.auth.model.jooq.tables.UsersRoles.UsersRolesPath
import com.advertisement.auth.model.jooq.tables.records.RolesRecord

import java.time.Instant

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Roles(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, RolesRecord>?,
    parentPath: InverseForeignKey<out Record, RolesRecord>?,
    aliased: Table<RolesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<RolesRecord>(
    alias,
    Advertisement.ADVERTISEMENT,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>advertisement.roles</code>
         */
        val ROLES: Roles = Roles()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<RolesRecord> = RolesRecord::class.java

    /**
     * The column <code>advertisement.roles.id</code>.
     */
    val ID: TableField<RolesRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>advertisement.roles.name</code>.
     */
    val NAME: TableField<RolesRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>advertisement.roles.created_at</code>.
     */
    val CREATED_AT: TableField<RolesRecord, Instant?> = createField(DSL.name("created_at"), SQLDataType.INSTANT.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<RolesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<RolesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<RolesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>advertisement.roles</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>advertisement.roles</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>advertisement.roles</code> table reference
     */
    constructor(): this(DSL.name("roles"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, RolesRecord>?, parentPath: InverseForeignKey<out Record, RolesRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, ROLES, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class RolesPath : Roles, Path<RolesRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, RolesRecord>?, parentPath: InverseForeignKey<out Record, RolesRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<RolesRecord>): super(alias, aliased)
        override fun `as`(alias: String): RolesPath = RolesPath(DSL.name(alias), this)
        override fun `as`(alias: Name): RolesPath = RolesPath(alias, this)
        override fun `as`(alias: Table<*>): RolesPath = RolesPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Advertisement.ADVERTISEMENT
    override fun getIdentity(): Identity<RolesRecord, Long?> = super.getIdentity() as Identity<RolesRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<RolesRecord> = ROLES_PKEY

    private lateinit var _usersRoles: UsersRolesPath

    /**
     * Get the implicit to-many join path to the
     * <code>advertisement.users_roles</code> table
     */
    fun usersRoles(): UsersRolesPath {
        if (!this::_usersRoles.isInitialized)
            _usersRoles = UsersRolesPath(this, null, USERS_ROLES__ROLE_ID_FK.inverseKey)

        return _usersRoles;
    }

    val usersRoles: UsersRolesPath
        get(): UsersRolesPath = usersRoles()
    override fun `as`(alias: String): Roles = Roles(DSL.name(alias), this)
    override fun `as`(alias: Name): Roles = Roles(alias, this)
    override fun `as`(alias: Table<*>): Roles = Roles(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Roles = Roles(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Roles = Roles(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Roles = Roles(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Roles = Roles(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Roles = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Roles = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Roles = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Roles = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Roles = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Roles = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Roles = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Roles = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Roles = where(DSL.notExists(select))
}
