/*
 * This file is generated by jOOQ.
 */
package com.advertisement.auth.model.jooq.tables.records


import com.advertisement.auth.model.jooq.tables.Roles

import java.time.Instant

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class RolesRecord() : UpdatableRecordImpl<RolesRecord>(Roles.ROLES) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var name: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var createdAt: Instant?
        set(value): Unit = set(2, value)
        get(): Instant? = get(2) as Instant?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised RolesRecord
     */
    constructor(id: Long? = null, name: String? = null, createdAt: Instant? = null): this() {
        this.id = id
        this.name = name
        this.createdAt = createdAt
        resetChangedOnNotNull()
    }
}
