/*
 * This file is generated by jOOQ.
 */
package com.advertisement.auth.model.jooq.tables.records


import com.advertisement.auth.model.jooq.tables.UsersRoles

import java.time.Instant
import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UsersRolesRecord() : UpdatableRecordImpl<UsersRolesRecord>(UsersRoles.USERS_ROLES) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var userId: UUID?
        set(value): Unit = set(1, value)
        get(): UUID? = get(1) as UUID?

    open var roleId: Long?
        set(value): Unit = set(2, value)
        get(): Long? = get(2) as Long?

    open var createdAt: Instant?
        set(value): Unit = set(3, value)
        get(): Instant? = get(3) as Instant?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised UsersRolesRecord
     */
    constructor(id: UUID? = null, userId: UUID? = null, roleId: Long? = null, createdAt: Instant? = null): this() {
        this.id = id
        this.userId = userId
        this.roleId = roleId
        this.createdAt = createdAt
        resetChangedOnNotNull()
    }
}
