/*
 * This file is generated by jOOQ.
 */
package com.advertisement.auth.model.jooq.tables.records


import com.advertisement.auth.model.jooq.tables.Users

import java.time.Instant
import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UsersRecord() : UpdatableRecordImpl<UsersRecord>(Users.USERS) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var phone: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var firstName: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var lastName: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var createdAt: Instant?
        set(value): Unit = set(4, value)
        get(): Instant? = get(4) as Instant?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised UsersRecord
     */
    constructor(id: UUID? = null, phone: String? = null, firstName: String? = null, lastName: String? = null, createdAt: Instant? = null): this() {
        this.id = id
        this.phone = phone
        this.firstName = firstName
        this.lastName = lastName
        this.createdAt = createdAt
        resetChangedOnNotNull()
    }
}
