/*
 * This file is generated by jOOQ.
 */
package com.advertisement.auth.model.jooq


import com.advertisement.auth.model.jooq.tables.AppClients
import com.advertisement.auth.model.jooq.tables.Otp
import com.advertisement.auth.model.jooq.tables.RefreshToken
import com.advertisement.auth.model.jooq.tables.Roles
import com.advertisement.auth.model.jooq.tables.Users
import com.advertisement.auth.model.jooq.tables.UsersRoles

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Advertisement : SchemaImpl("advertisement", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>advertisement</code>
         */
        val ADVERTISEMENT: Advertisement = Advertisement()
    }

    /**
     * The table <code>advertisement.app_clients</code>.
     */
    val APP_CLIENTS: AppClients get() = AppClients.APP_CLIENTS

    /**
     * The table <code>advertisement.otp</code>.
     */
    val OTP: Otp get() = Otp.OTP

    /**
     * The table <code>advertisement.refresh_token</code>.
     */
    val REFRESH_TOKEN: RefreshToken get() = RefreshToken.REFRESH_TOKEN

    /**
     * The table <code>advertisement.roles</code>.
     */
    val ROLES: Roles get() = Roles.ROLES

    /**
     * The table <code>advertisement.users</code>.
     */
    val USERS: Users get() = Users.USERS

    /**
     * The table <code>advertisement.users_roles</code>.
     */
    val USERS_ROLES: UsersRoles get() = UsersRoles.USERS_ROLES

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        AppClients.APP_CLIENTS,
        Otp.OTP,
        RefreshToken.REFRESH_TOKEN,
        Roles.ROLES,
        Users.USERS,
        UsersRoles.USERS_ROLES
    )
}
